CUDA_VISIBLE_DEVICES=7 python main.py AG16ft --data_path ./data/agnews_c2f --dataset BERT --seed 86548 --batch_size 64 --lr 0.0005 --encode_length 16 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.5 --n-class 4 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --num_bad_epochs 10 --proto_tau 0.7 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 1 --prob_weight 0.5 --KL_weight 1  --multi_queue --train --code_weight 2 --fine_cluster_nums 20 --nclusters 4
CUDA_VISIBLE_DEVICES=7 python main.py AG32ft --data_path ./data/agnews_c2f --dataset BERT --seed 86548 --batch_size 64 --lr 0.0001 --encode_length 32 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.5 --n-class 4 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --num_bad_epochs 10 --proto_tau 0.7 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 1 --prob_weight 0.5 --KL_weight 1  --multi_queue --train --code_weight 2 --fine_cluster_nums 20 --nclusters 4
CUDA_VISIBLE_DEVICES=7 python main.py AG64ft --data_path ./data/agnews_c2f --dataset BERT --seed 86548 --batch_size 64 --lr 0.0001 --encode_length 64 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.5 --n-class 4 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --num_bad_epochs 10 --proto_tau 0.7 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 1 --prob_weight 0.5 --KL_weight 1  --multi_queue --train --code_weight 2 --fine_cluster_nums 20 --nclusters 4
CUDA_VISIBLE_DEVICES=7 python main.py AG128ft --data_path ./data/agnews_c2f --dataset BERT --seed 86548 --batch_size 64 --lr 0.0001 --encode_length 128 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.5 --n-class 4 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --num_bad_epochs 10 --proto_tau 0.7 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 1 --prob_weight 0.5 --KL_weight 1  --multi_queue --train --code_weight 2 --fine_cluster_nums 20 --nclusters 4

CUDA_VISIBLE_DEVICES=0 python main.py DB16ft --data_path ./data/dbpedia --dataset BERT --seed 86548 --batch_size 64 --lr 0.0005 --encode_length 16 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.3 --n-class 9 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --num_bad_epochs 10 --proto_tau 0.5 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 0.5 --prob_weight 0.5 --KL_weight 1  --multi_queue --train --code_weight 5 --ys_weight 0.5
CUDA_VISIBLE_DEVICES=0 python main.py DB32ft --data_path ./data/dbpedia --dataset BERT --seed 86548 --batch_size 64 --lr 0.0005 --encode_length 32 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.3 --n-class 9 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --num_bad_epochs 10 --proto_tau 0.5 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 0.5 --prob_weight 0.5 --KL_weight 1  --multi_queue --train --code_weight 5 --ys_weight 0.5
CUDA_VISIBLE_DEVICES=0 python main.py DB64ft --data_path ./data/dbpedia --dataset BERT --seed 86548 --batch_size 64 --lr 0.0005 --encode_length 64 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.3 --n-class 9 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --num_bad_epochs 10 --proto_tau 0.5 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 0.5 --prob_weight 0.5 --KL_weight 1  --multi_queue --train --code_weight 5 --ys_weight 0.5
CUDA_VISIBLE_DEVICES=0 python main.py DB128ft --data_path ./data/dbpedia --dataset BERT --seed 86548 --batch_size 64 --lr 0.0005 --encode_length 128 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.3 --n-class 9 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --num_bad_epochs 10 --proto_tau 0.5 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 0.5 --prob_weight 0.5 --KL_weight 1  --multi_queue --train --code_weight 5 --ys_weight 0.5

CUDA_VISIBLE_DEVICES=6 python main.py NYT64 --data_path ./data/nyt_c2f --dataset BERT --seed 86548 --batch_size 64 --lr 0.0001 --encode_length 64 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.3 --n-class 5 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --proto_tau 0.5 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 1 --prob_weight 0 --KL_weight 1  --multi_queue --code_weight 1  --continue_training --fine_cluster_nums 100
CUDA_VISIBLE_DEVICES=6 python main.py NYT16 --data_path ./data/nyt_c2f --dataset BERT --seed 86548 --batch_size 64 --lr 0.0001 --encode_length 16 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.3 --n-class 5 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --proto_tau 0.5 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 1 --prob_weight 0 --KL_weight 1  --multi_queue --code_weight 1  --continue_training --fine_cluster_nums 100
CUDA_VISIBLE_DEVICES=6 python main.py NYT32 --data_path ./data/nyt_c2f --dataset BERT --seed 86548 --batch_size 64 --lr 0.0001 --encode_length 32 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.3 --n-class 5 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --proto_tau 0.5 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 1 --prob_weight 0 --KL_weight 1  --multi_queue --code_weight 1  --continue_training --fine_cluster_nums 100
CUDA_VISIBLE_DEVICES=6 python main.py NYT128 --data_path ./data/nyt_c2f --dataset BERT --seed 86548 --batch_size 64 --lr 0.0001 --encode_length 128 --cuda --workers 0 --max_length 200 --hiddim 128 --c2f --tau 0.3 --n-class 5 --hashing_alpha 1.0 --gumbel_temperature 1 --consis_temperature 5 --dropout_rate 0.3 --pooler_type cls --proto_tau 0.5 --yz_tau 1.0 --pretrain_epoch 1 --cond_ent_weight 0.1 --VAE_weight 1 --prob_weight 0 --KL_weight 1  --multi_queue --code_weight 1  --continue_training --fine_cluster_nums 100